import type { Dictionary } from "./es";

const ca: Dictionary = {
  nav: {
    home: "Inici",
    about: "Nosaltres",
    services: "Serveis",
    contact: "Contacte",
    quote: "Pressupost",
    cta: "Demana pressupost",
    menu: "Obre el menú",
    close: "Tanca el menú",
    language: "Idioma",
    skip: "Salta al contingut",
    call: "Truca",
  },
  home: {
    meta: {
      title: "Retirada d'amiant i renovació de cobertes a Catalunya | Eco-Reti 2030",
      description:
        "Empresa inscrita al RERA especialitzada en retirada d'amiant (uralita), substitució de cobertes i gestió de residus a Girona i a tot Catalunya. Demana el teu pressupost.",
    },
    hero: {
      eyebrow: "Empresa inscrita al RERA · Girona i tot Catalunya",
      title: "Retirem l'amiant.",
      titleAccent: "Renovem la teva coberta.",
      lead: "Desmuntatge segur de cobertes de fibrociment (uralita), gestió de residus i coberta nova, eficient i amb garantia. Ens n'ocupem de tot, del pla de treball a l'últim certificat.",
      ctaPrimary: "Demana pressupost",
      ctaSecondary: "Veure serveis",
      imageAlt: "Retirada de plaques de fibrociment amb amiant a la coberta d'una nau industrial amb plaques solars",
    },
    stats: [
      { value: 15, prefix: "+", suffix: "", decimals: 0, label: "anys d'experiència" },
      { value: 300, prefix: "+", suffix: "", decimals: 0, label: "projectes realitzats" },
      { value: 4.8, prefix: "", suffix: "/5", decimals: 1, label: "valoració mitjana" },
      { value: 100, prefix: "", suffix: "%", decimals: 0, label: "clients satisfets" },
    ],
    intro: {
      eyebrow: "Solucions professionals",
      title: "Un sol equip, de la primera visita a la coberta nova",
      text: "Acompanyem particulars, comunitats de propietaris i empreses durant tot el procés. Estudiem cada cas de manera personalitzada per oferir una solució segura, eficient i adaptada a cada immoble.",
      cta: "Coneix Eco-Reti",
    },
    services: {
      eyebrow: "Serveis",
      title: "Tot el que cal per renovar la coberta amb seguretat",
      cta: "Veure tots els serveis",
    },
    process: {
      eyebrow: "Com treballem",
      title: "Quatre passos, cap sorpresa",
      steps: [
        { title: "Visita tècnica", text: "Inspeccionem la coberta, prenem mides i valorem l'estat del material per donar-te un pressupost clar." },
        { title: "Pla de treball", text: "Redactem el pla de treball i el presentem a l'autoritat laboral perquè l'aprovi, tal com exigeix el RD 396/2006." },
        { title: "Retirada segura", text: "Desmuntem, encapsulem i etiquetem l'amiant amb equips de protecció i mesures per evitar que s'alliberin fibres." },
        { title: "Coberta nova", text: "Instal·lem la coberta nova, gestionem els residus fins a un abocador autoritzat i et lliurem tota la documentació." },
      ],
    },
    why: {
      eyebrow: "Per què Eco-Reti 2030",
      title: "La tranquil·litat de fer-ho bé",
      items: [
        { title: "Experiència", text: "Equip especialitzat en retirada d'amiant i renovació de cobertes." },
        { title: "Seguretat", text: "Procediments segurs i una planificació rigorosa en cada intervenció." },
        { title: "Gestió integral", text: "Permisos, documentació i residus: ens ocupem de tot el procés." },
        { title: "Tracte proper", text: "T'acompanyem abans, durant i després de l'obra." },
      ],
    },
    sectors: {
      eyebrow: "On treballem",
      title: "Cada immoble, la seva solució",
      items: ["Habitatges", "Comunitats de propietaris", "Naus industrials", "Explotacions agrícoles i ramaderes", "Edificis comercials"],
    },
    testimonials: {
      eyebrow: "Opinions",
      title: "El que diuen els nostres clients",
      items: [
        { quote: "Des del primer contacte ens van transmetre molta confiança. Tot el procés va estar perfectament organitzat i el resultat va ser excel·lent.", author: "Marta G.", city: "Barcelona" },
        { quote: "Ens van explicar cada pas amb claredat i van substituir la coberta en el termini previst.", author: "Carlos R.", city: "Girona" },
        { quote: "Un equip molt professional i proper. Es van encarregar de tota la gestió i la feina va quedar impecable.", author: "Laura M.", city: "Tarragona" },
        { quote: "Recomanables al cent per cent. Comunicació constant i un acabat de gran qualitat.", author: "David P.", city: "Lleida" },
      ],
    },
    faq: {
      eyebrow: "Preguntes freqüents",
      title: "El que convé saber sobre l'amiant",
    },
    cta: {
      title: "Tens una coberta d'uralita?",
      text: "Explica'ns el teu cas i et prepararem una proposta adaptada, amb total transparència des del primer moment.",
      button: "Demana pressupost",
    },
  },
  bottle: {
    eyebrow: "El nostre compromís",
    title: "Avancem cap a un futur més",
    accent: "segur.",
    lead: "La nostra ampolla reutilitzable porta imprès el que guia cada obra: persones, entorns i solucions sostenibles.",
    values: ["Retirar amb seguretat", "Protegir les persones", "Recuperar els entorns", "Construir un demà més sostenible"],
    claim: "Compromesos amb les persones i el territori.",
    imageAlt: "Ampolla de vidre reutilitzable d'Eco-Reti amb tap metàl·lic i cordó taronja, vista frontal i posterior",
  },
  services: {
    meta: {
      title: "Serveis: retirada d'amiant, cobertes i eficiència | Eco-Reti 2030",
      description:
        "Retirada d'amiant i uralita, substitució de cobertes per panell sandvitx, gestió integral de permisos i residus i millora de l'eficiència energètica a Catalunya.",
    },
    title: "Serveis i solucions",
    lead: "Solucions integrals per retirar l'amiant, renovar la coberta i millorar l'eficiència de tot tipus d'immobles, amb seguretat, qualitat i un servei personalitzat.",
    items: [
      {
        id: "retirada-amiant",
        title: "Retirada d'amiant",
        short: "Desmuntatge segur d'elements amb amiant seguint els protocols establerts.",
        text: "Retirem cobertes de fibrociment (uralita), dipòsits, baixants, conductes i altres elements que contenen amiant. Treballem amb un pla de treball aprovat, equips de protecció i una gestió correcta dels residus per protegir les persones i el medi ambient.",
        points: ["Cobertes de fibrociment i uralita", "Dipòsits, baixants i conductes", "Encapsulat i etiquetatge del residu", "Transport a abocador autoritzat"],
        image: "/images/coberta-fibrociment-amiant-nau-industrial.jpg",
        imageAlt: "Coberta de fibrociment amb amiant en una nau industrial abans de retirar-la",
      },
      {
        id: "renovacio-cobertes",
        title: "Renovació de cobertes",
        short: "Substitució de cobertes velles per solucions modernes, resistents i eficients.",
        text: "Substituïm les cobertes deteriorades per solucions modernes com el panell sandvitx, que milloren l'aïllament, l'estanquitat, la seguretat i la durabilitat de l'edifici, adaptant-nos a cada projecte.",
        points: ["Panell sandvitx i xapa", "Més aïllament tèrmic i acústic", "Canals i remats", "Preparada per a plaques solars"],
        image: "/images/coberta-nova-panell-sandvitx.jpg",
        imageAlt: "Coberta nova de panell sandvitx instal·lada en una nau",
      },
      {
        id: "gestio-integral",
        title: "Gestió integral",
        short: "Coordinem permisos, documentació i gestió de residus durant tot el projecte.",
        text: "Coordinem totes les fases de la intervenció, des de la visita tècnica inicial fins a la tramitació del pla de treball, els permisos municipals i la documentació de la gestió de residus. Una solució completa i sense preocupacions.",
        points: ["Visita tècnica i pressupost", "Pla de treball davant l'autoritat laboral", "Llicències i permisos", "Certificats de gestió de residus"],
        image: "/images/residus-amiant-encapsulats.jpg",
        imageAlt: "Plaques d'amiant retirades, encapsulades amb plàstic i etiquetades sobre palets",
      },
      {
        id: "eficiencia-energetica",
        title: "Eficiència energètica",
        short: "Millorem l'aïllament i preparem la coberta per a futures solucions energètiques.",
        text: "Aprofitem la renovació de la coberta per millorar l'aïllament i deixar l'immoble preparat per instal·lar plaques solars, amb més confort i menys consum energètic.",
        points: ["Aïllament de l'envolupant", "Coberta a punt per a fotovoltaica", "Menys pèrdues de calor", "Més confort a l'estiu i a l'hivern"],
        image: "/images/eficiencia-energetica-coberta.jpg",
        imageAlt: "Coberta renovada al costat d'una coberta amb plaques solars",
      },
    ],
    where: {
      title: "On treballem",
      text: "Donem servei a habitatges, comunitats de propietaris, naus industrials, explotacions agrícoles i edificis comercials de les quatre demarcacions de Catalunya, adaptant-nos a les característiques de cada immoble.",
    },
  },
  about: {
    meta: {
      title: "Qui som | Eco-Reti 2030, retirada d'amiant a Girona",
      description:
        "Equip especialitzat en retirada d'amiant, renovació de cobertes i eficiència d'immobles amb seu a Fornells de la Selva (Girona). Seguretat, transparència i proximitat.",
    },
    title: "Qui som",
    lead: "Som un equip especialitzat en la retirada d'amiant, la renovació de cobertes i la millora de l'eficiència dels immobles. Treballem amb compromís, seguretat i proximitat, acompanyant el client durant tot el procés.",
    teamTitle: "El nostre equip",
    teamText: "Professionals especialitzats que treballen de manera coordinada per oferir un servei segur, eficient i de qualitat en cada intervenció.",
    team: [
      { title: "Assessorament tècnic", text: "Estudiem cada projecte per oferir la solució més adequada des del primer moment." },
      { title: "Planificació de l'obra", text: "Organitzem cada intervenció per garantir seguretat, eficiència i compliment dels terminis." },
      { title: "Execució especialitzada", text: "Cada treball segueix els protocols establerts i utilitza materials de màxima qualitat." },
      { title: "Atenció personalitzada", text: "T'acompanyem abans, durant i després de l'obra per resoldre qualsevol dubte." },
    ],
    trustTitle: "Confiança i experiència",
    trustText: "Cada projecte reflecteix el nostre compromís amb la seguretat, la transparència i la satisfacció dels nostres clients.",
    reraTitle: "Inscrits al RERA",
    reraText: "Estem inscrits al Registre d'Empreses amb Risc d'Amiant, requisit legal per a qualsevol empresa que retiri o manipuli materials amb amiant.",
  },
  contact: {
    meta: {
      title: "Contacte | Eco-Reti 2030",
      description: "Contacta amb Eco-Reti 2030 per retirar amiant o renovar la coberta. Telèfon +34 621 041 628, info@ecoreti2030.com. Fornells de la Selva (Girona).",
    },
    title: "Contacte",
    lead: "Som aquí per ajudar-te amb la retirada d'amiant, la renovació de cobertes o qualsevol consulta. Explica'ns el teu projecte i et respondrem tan aviat com puguem.",
    infoTitle: "Informació de contacte",
    phone: "Telèfon",
    email: "Escriu-nos",
    hours: "Horari",
    hoursValue: "De dilluns a divendres, de 8:00 a 17:00",
    area: "Zona d'actuació",
    areaValue: "Tot Catalunya",
    address: "Adreça",
    whatsapp: "Escriu-nos per WhatsApp",
  },
  quote: {
    meta: {
      title: "Demana pressupost per retirar amiant o canviar la coberta | Eco-Reti 2030",
      description: "Sol·licita un pressupost personalitzat per retirar amiant o uralita i renovar la coberta a Catalunya. Et responem amb una proposta adaptada al teu immoble.",
    },
    title: "Sol·licita el teu pressupost",
    lead: "Explica'ns els detalls del projecte i et prepararem una proposta personalitzada, adaptada al teu immoble i als serveis que necessites.",
    steps: ["Ens envies les dades", "Et truquem i concertem la visita", "Reps un pressupost detallat"],
  },
  form: {
    name: "Nom i cognoms",
    email: "Correu electrònic",
    phone: "Telèfon",
    propertyType: "Tipus d'immoble",
    municipality: "Municipi",
    surface: "Superfície aproximada",
    service: "Servei que necessites",
    message: "Missatge",
    messageQuote: "Detalls del projecte (opcional)",
    messagePlaceholder: "Estat de la coberta, accessos, terminis… tot el que ens ajudi a entendre el teu cas.",
    privacy: "He llegit i accepto la",
    privacyLink: "política de privacitat",
    required: "obligatori",
    select: "Tria una opció",
    submit: "Envia la sol·licitud",
    submitContact: "Envia la consulta",
    sending: "Enviant…",
    successTitle: "Sol·licitud enviada!",
    successText: "Gràcies. Hem rebut el teu missatge i et respondrem tan aviat com puguem.",
    errorGeneric: "No hem pogut enviar el formulari. Torna-ho a provar o truca'ns al",
    errors: {
      name: "Indica el teu nom.",
      email: "Indica un correu electrònic vàlid.",
      phone: "Indica un telèfon vàlid.",
      propertyType: "Tria el tipus d'immoble.",
      municipality: "Indica el municipi.",
      service: "Tria un servei.",
      message: "Escriu el teu missatge.",
      privacy: "Has d'acceptar la política de privacitat.",
    },
    propertyTypes: {
      house: "Habitatge",
      community: "Comunitat de propietaris",
      industrial: "Nau industrial",
      agricultural: "Explotació agrícola o ramadera",
      commercial: "Edifici comercial",
      other: "Altres",
    },
    surfaces: {
      lt50: "Menys de 50 m²",
      "50-200": "Entre 50 i 200 m²",
      "200-1000": "Entre 200 i 1.000 m²",
      gt1000: "Més de 1.000 m²",
      unknown: "No ho sé",
    },
    services: {
      asbestos: "Retirada d'amiant",
      roof: "Renovació de coberta",
      both: "Retirada d'amiant i coberta nova",
      efficiency: "Eficiència energètica",
      advice: "Assessorament",
    },
  },
  footer: {
    about: "Empresa especialitzada en la retirada d'amiant, la renovació de cobertes i la millora de l'eficiència dels immobles. Un servei professional, segur i proper en cada projecte.",
    links: "Enllaços",
    contact: "Contacte",
    legal: "Avís legal",
    privacy: "Política de privacitat",
    cookies: "Política de galetes",
    funding: "Projecte finançat pel programa Kit Digital, amb fons Next Generation EU del Pla de Recuperació, Transformació i Resiliència.",
    rights: "Tots els drets reservats.",
  },
  notFound: { title: "Pàgina no trobada", text: "La pàgina que busques no existeix o ha canviat d'adreça.", back: "Torna a l'inici" },
  breadcrumbHome: "Inici",
};

export default ca;
