// Textos en castellà. El tipus `Dictionary` es deriva d'aquest objecte i el català l'ha de complir.
const es = {
  nav: {
    home: "Inicio",
    about: "Nosotros",
    services: "Servicios",
    contact: "Contacto",
    quote: "Presupuesto",
    cta: "Pedir presupuesto",
    menu: "Abrir menú",
    close: "Cerrar menú",
    language: "Idioma",
    skip: "Saltar al contenido",
    call: "Llamar",
  },
  home: {
    meta: {
      title: "Retirada de amianto y renovación de cubiertas en Cataluña | Eco-Reti 2030",
      description:
        "Empresa inscrita en el RERA especializada en retirada de amianto (uralita), sustitución de cubiertas y gestión de residuos en Girona y toda Cataluña. Pide tu presupuesto.",
    },
    hero: {
      title: "Retiramos el amianto.",
      titleAccent: "Renovamos tu cubierta.",
      lead: "Desmontaje seguro de cubiertas de fibrocemento (uralita), gestión de residuos y cubierta nueva, eficiente y con garantía. Nos ocupamos de todo, del plan de trabajo al último certificado.",
      ctaPrimary: "Pedir presupuesto",
      ctaSecondary: "Ver servicios",
      imageAlt: "Retirada de placas de fibrocemento con amianto en la cubierta de una nave industrial con placas solares",
    },
    stats: [
      { value: 15, prefix: "+", suffix: "", decimals: 0, label: "años de experiencia" },
      { value: 300, prefix: "+", suffix: "", decimals: 0, label: "proyectos realizados" },
      { value: 4.8, prefix: "", suffix: "/5", decimals: 1, label: "valoración media" },
      { value: 100, prefix: "", suffix: "%", decimals: 0, label: "clientes satisfechos" },
    ],
    intro: {
      eyebrow: "Soluciones profesionales",
      title: "Un solo equipo, de la primera visita a la cubierta nueva",
      text: "Acompañamos a particulares, comunidades de propietarios y empresas durante todo el proceso. Estudiamos cada caso de forma personalizada para ofrecer una solución segura, eficiente y adaptada a cada inmueble.",
      cta: "Conocer Eco-Reti",
    },
    services: {
      eyebrow: "Servicios",
      title: "Todo lo necesario para renovar tu cubierta con seguridad",
      cta: "Ver todos los servicios",
    },
    process: {
      eyebrow: "Cómo trabajamos",
      title: "Cuatro pasos, cero sorpresas",
      steps: [
        { title: "Visita técnica", text: "Inspeccionamos la cubierta, medimos y valoramos el estado del material para darte un presupuesto claro." },
        { title: "Plan de trabajo", text: "Redactamos el plan de trabajo y lo presentamos a la autoridad laboral para su aprobación, como exige el RD 396/2006." },
        { title: "Retirada segura", text: "Desmontamos, encapsulamos y etiquetamos el amianto con equipos de protección y medidas para evitar la liberación de fibras." },
        { title: "Cubierta nueva", text: "Instalamos la nueva cubierta, gestionamos los residuos hasta un vertedero autorizado y te entregamos toda la documentación." },
      ],
    },
    why: {
      eyebrow: "Por qué Eco-Reti 2030",
      title: "La tranquilidad de hacerlo bien",
      items: [
        { title: "Experiencia", text: "Equipo especializado en retirada de amianto y renovación de cubiertas." },
        { title: "Seguridad", text: "Procedimientos seguros y una planificación rigurosa en cada intervención." },
        { title: "Gestión integral", text: "Permisos, documentación y residuos: nos ocupamos de todo el proceso." },
        { title: "Trato cercano", text: "Te acompañamos antes, durante y después de la obra." },
      ],
    },
    sectors: {
      eyebrow: "Dónde trabajamos",
      title: "Cada inmueble, su solución",
      items: ["Viviendas", "Comunidades de propietarios", "Naves industriales", "Explotaciones agrícolas y ganaderas", "Edificios comerciales"],
    },
    testimonials: {
      eyebrow: "Opiniones",
      title: "Lo que dicen nuestros clientes",
      items: [
        { quote: "Desde el primer contacto nos transmitieron mucha confianza. Todo el proceso estuvo perfectamente organizado y el resultado fue excelente.", author: "Marta G.", city: "Barcelona" },
        { quote: "Nos explicaron cada paso con claridad y realizaron la sustitución de la cubierta en el plazo previsto.", author: "Carlos R.", city: "Girona" },
        { quote: "Un equipo muy profesional y cercano. Se encargaron de toda la gestión y el trabajo quedó impecable.", author: "Laura M.", city: "Tarragona" },
        { quote: "Recomendables al cien por cien. Comunicación constante y un acabado de gran calidad.", author: "David P.", city: "Lleida" },
      ],
    },
    faq: {
      eyebrow: "Preguntas frecuentes",
      title: "Lo que conviene saber sobre el amianto",
    },
    cta: {
      title: "¿Tienes una cubierta de uralita?",
      text: "Cuéntanos tu caso y te preparamos una propuesta adaptada, con total transparencia desde el primer momento.",
      button: "Pedir presupuesto",
    },
  },
  roof: {
    eyebrow: "Así trabajamos",
    title: "De la uralita",
    accent: "al sol.",
    lead: "Retiramos la cubierta de fibrocemento con amianto, instalamos una cubierta nueva y la dejamos lista para producir energía.",
    steps: [
      { title: "Cubierta de uralita", text: "Fibrocemento con amianto, envejecido y frágil." },
      { title: "Retirada segura", text: "Placa a placa, con plan de trabajo aprobado y el residuo encapsulado." },
      { title: "Cubierta nueva", text: "Panel sándwich aislante, estanco y duradero." },
      { title: "Placas solares", text: "La cubierta queda lista para generar energía limpia." },
    ],
    imageAlt: "Nave industrial con la cubierta de fibrocemento en proceso de retirada y placas solares instaladas",
  },
  bottle: {
    eyebrow: "Nuestro compromiso",
    title: "Avanzamos hacia un futuro más",
    accent: "seguro.",
    lead: "Nuestra botella reutilizable lleva impreso lo que guía cada obra: personas, entornos y soluciones sostenibles.",
    values: ["Retirar con seguridad", "Proteger a las personas", "Recuperar los entornos", "Construir un mañana más sostenible"],
    claim: "Comprometidos con las personas y el territorio.",
    imageAlt: "Botella de cristal reutilizable de Eco-Reti con tapón metálico y cordón naranja, vista frontal y posterior",
  },
  services: {
    meta: {
      title: "Servicios: retirada de amianto, cubiertas y eficiencia | Eco-Reti 2030",
      description:
        "Retirada de amianto y uralita, sustitución de cubiertas por panel sándwich, gestión integral de permisos y residuos y mejora de la eficiencia energética en Cataluña.",
    },
    title: "Servicios y soluciones",
    lead: "Soluciones integrales para retirar el amianto, renovar la cubierta y mejorar la eficiencia de todo tipo de inmuebles, con seguridad, calidad y un servicio personalizado.",
    items: [
      {
        id: "retirada-amianto",
        title: "Retirada de amianto",
        short: "Desmontaje seguro de elementos con amianto siguiendo los protocolos establecidos.",
        text: "Retiramos cubiertas de fibrocemento (uralita), depósitos, bajantes, conductos y otros elementos que contienen amianto. Trabajamos con un plan de trabajo aprobado, equipos de protección y una gestión correcta de los residuos para proteger a las personas y al medio ambiente.",
        points: ["Cubiertas de fibrocemento y uralita", "Depósitos, bajantes y conductos", "Encapsulado y etiquetado del residuo", "Transporte a vertedero autorizado"],
        image: "/images/coberta-fibrociment-amiant-nau-industrial.jpg",
        imageAlt: "Cubierta de fibrocemento con amianto en una nave industrial antes de su retirada",
      },
      {
        id: "renovacion-cubiertas",
        title: "Renovación de cubiertas",
        short: "Sustitución de cubiertas antiguas por soluciones modernas, resistentes y eficientes.",
        text: "Sustituimos las cubiertas deterioradas por soluciones modernas como el panel sándwich, que mejoran el aislamiento, la estanqueidad, la seguridad y la durabilidad del edificio, adaptándonos a cada proyecto.",
        points: ["Panel sándwich y chapa", "Mejor aislamiento térmico y acústico", "Canalones y remates", "Preparada para placas solares"],
        image: "/images/coberta-nova-panell-sandvitx.jpg",
        imageAlt: "Cubierta nueva de panel sándwich instalada en una nave",
      },
      {
        id: "gestion-integral",
        title: "Gestión integral",
        short: "Coordinamos permisos, documentación y gestión de residuos durante todo el proyecto.",
        text: "Coordinamos todas las fases de la intervención, desde la visita técnica inicial hasta la tramitación del plan de trabajo, los permisos municipales y la documentación de la gestión de residuos. Una solución completa y sin preocupaciones.",
        points: ["Visita técnica y presupuesto", "Plan de trabajo ante la autoridad laboral", "Licencias y permisos", "Certificados de gestión de residuos"],
        image: "/images/residus-amiant-encapsulats.jpg",
        imageAlt: "Placas de amianto retiradas, encapsuladas en plástico y etiquetadas sobre palés",
      },
      {
        id: "eficiencia-energetica",
        title: "Eficiencia energética",
        short: "Mejoramos el aislamiento y preparamos la cubierta para futuras soluciones energéticas.",
        text: "Aprovechamos la renovación de la cubierta para mejorar el aislamiento y dejar el inmueble preparado para instalar placas solares, aumentando el confort y reduciendo el consumo energético.",
        points: ["Aislamiento de la envolvente", "Cubierta lista para fotovoltaica", "Menos pérdidas de calor", "Más confort en verano e invierno"],
        image: "/images/eficiencia-energetica-coberta.jpg",
        imageAlt: "Cubierta renovada junto a una cubierta con placas solares",
      },
    ],
    where: {
      title: "Dónde trabajamos",
      text: "Damos servicio a viviendas, comunidades de propietarios, naves industriales, explotaciones agrícolas y edificios comerciales en las cuatro provincias de Cataluña, adaptándonos a las características de cada inmueble.",
    },
  },
  about: {
    meta: {
      title: "Quiénes somos | Eco-Reti 2030, retirada de amianto en Girona",
      description:
        "Equipo especializado en retirada de amianto, renovación de cubiertas y eficiencia de inmuebles con sede en Fornells de la Selva (Girona). Seguridad, transparencia y cercanía.",
    },
    title: "Quiénes somos",
    lead: "Somos un equipo especializado en la retirada de amianto, la renovación de cubiertas y la mejora de la eficiencia de los inmuebles. Trabajamos con compromiso, seguridad y cercanía, acompañando al cliente durante todo el proceso.",
    teamTitle: "Nuestro equipo",
    teamText: "Profesionales especializados que trabajan de forma coordinada para ofrecer un servicio seguro, eficiente y de calidad en cada intervención.",
    team: [
      { title: "Asesoramiento técnico", text: "Estudiamos cada proyecto para ofrecer la solución más adecuada desde el primer momento." },
      { title: "Planificación de la obra", text: "Organizamos cada intervención para garantizar seguridad, eficiencia y cumplimiento de plazos." },
      { title: "Ejecución especializada", text: "Cada trabajo sigue los protocolos establecidos y utiliza materiales de máxima calidad." },
      { title: "Atención personalizada", text: "Te acompañamos antes, durante y después de la obra para resolver cualquier duda." },
    ],
    trustTitle: "Confianza y experiencia",
    trustText: "Cada proyecto refleja nuestro compromiso con la seguridad, la transparencia y la satisfacción de nuestros clientes.",
    reraTitle: "Inscritos en el RERA",
    reraText: "Estamos inscritos en el Registro de Empresas con Riesgo de Amianto, requisito legal para cualquier empresa que retire o manipule materiales con amianto.",
  },
  contact: {
    meta: {
      title: "Contacto | Eco-Reti 2030",
      description: "Contacta con Eco-Reti 2030 para retirar amianto o renovar tu cubierta. Teléfono +34 621 041 628, info@ecoreti2030.com. Fornells de la Selva (Girona).",
    },
    title: "Contacto",
    lead: "Estamos aquí para ayudarte con la retirada de amianto, la renovación de cubiertas o cualquier consulta. Cuéntanos tu proyecto y te responderemos lo antes posible.",
    infoTitle: "Información de contacto",
    phone: "Teléfono",
    email: "Escríbenos",
    hours: "Horario",
    hoursValue: "Lunes a viernes, de 8:00 a 17:00",
    area: "Zona de actuación",
    areaValue: "Toda Cataluña",
    address: "Dirección",
    whatsapp: "Escríbenos por WhatsApp",
  },
  quote: {
    meta: {
      title: "Pide presupuesto para retirar amianto o cambiar la cubierta | Eco-Reti 2030",
      description: "Solicita un presupuesto personalizado para retirar amianto o uralita y renovar tu cubierta en Cataluña. Te respondemos con una propuesta adaptada a tu inmueble.",
    },
    title: "Solicita tu presupuesto",
    lead: "Cuéntanos los detalles de tu proyecto y prepararemos una propuesta personalizada, adaptada a tu inmueble y a los servicios que necesitas.",
    steps: ["Nos envías los datos", "Te llamamos y concertamos la visita", "Recibes un presupuesto detallado"],
  },
  form: {
    name: "Nombre y apellidos",
    email: "Correo electrónico",
    phone: "Teléfono",
    propertyType: "Tipo de inmueble",
    municipality: "Municipio",
    surface: "Superficie aproximada",
    service: "Servicio que necesitas",
    message: "Mensaje",
    messageQuote: "Detalles del proyecto (opcional)",
    messagePlaceholder: "Estado de la cubierta, accesos, plazos… todo lo que nos ayude a entender tu caso.",
    privacy: "He leído y acepto la",
    privacyLink: "política de privacidad",
    required: "obligatorio",
    select: "Selecciona una opción",
    submit: "Enviar solicitud",
    submitContact: "Enviar consulta",
    sending: "Enviando…",
    successTitle: "¡Solicitud enviada!",
    successText: "Gracias. Hemos recibido tu mensaje y te responderemos lo antes posible.",
    errorGeneric: "No hemos podido enviar el formulario. Inténtalo de nuevo o llámanos al",
    errors: {
      name: "Indica tu nombre.",
      email: "Indica un correo electrónico válido.",
      phone: "Indica un teléfono válido.",
      propertyType: "Selecciona el tipo de inmueble.",
      municipality: "Indica el municipio.",
      service: "Selecciona un servicio.",
      message: "Escribe tu mensaje.",
      privacy: "Debes aceptar la política de privacidad.",
    },
    propertyTypes: {
      house: "Vivienda",
      community: "Comunidad de propietarios",
      industrial: "Nave industrial",
      agricultural: "Explotación agrícola o ganadera",
      commercial: "Edificio comercial",
      other: "Otro",
    },
    surfaces: {
      lt50: "Menos de 50 m²",
      "50-200": "Entre 50 y 200 m²",
      "200-1000": "Entre 200 y 1.000 m²",
      gt1000: "Más de 1.000 m²",
      unknown: "No lo sé",
    },
    services: {
      asbestos: "Retirada de amianto",
      roof: "Renovación de cubierta",
      both: "Retirada de amianto y cubierta nueva",
      efficiency: "Eficiencia energética",
      advice: "Asesoramiento",
    },
  },
  footer: {
    about: "Empresa especializada en la retirada de amianto, la renovación de cubiertas y la mejora de la eficiencia de los inmuebles. Un servicio profesional, seguro y cercano en cada proyecto.",
    links: "Enlaces",
    contact: "Contacto",
    legal: "Aviso legal",
    privacy: "Política de privacidad",
    cookies: "Política de cookies",
    funding: "Proyecto financiado por el programa Kit Digital, con fondos Next Generation EU del Plan de Recuperación, Transformación y Resiliencia.",
    rights: "Todos los derechos reservados.",
  },
  notFound: { title: "Página no encontrada", text: "La página que buscas no existe o ha cambiado de dirección.", back: "Volver al inicio" },
  breadcrumbHome: "Inicio",
};

export default es;
export type Dictionary = typeof es;
